version: "3.8"
services:
  dashboard:
    command: 'bundle exec rails s -b 0.0.0.0'
    env_file:
      - './apps/pulsechecker_dashboard/.env.docker'
    build:
      context: ./apps/pulsechecker_dashboard
    volumes:
      - ./apps/pulsechecker_dashboard:/code
      - /code/node_modules/
    depends_on:
      - postgres
      - redis
      - smtp
      - webpacker
    ports:
      - "3000:3000"
  webpacker:
    build:
      context: ./apps/pulsechecker_dashboard
    command: 'bin/webpack-dev-server --hot'
    volumes:
      - ./apps/pulsechecker_dashboard:/code
      - /code/node_modules/
    ports:
      - 3035:3035
  agent:
    command: 'yarn run dev'
    build:
      context: ./apps/pulsechecker_agent
    volumes:
      - ./apps/pulsechecker_agent/src:/code/src
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
  smtp:
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: none

  postgres:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    ports:
      - "5544:5432"
    environment:
      POSTGRES_PASSWORD: 123456
  #    logging:
  #      driver: none

  redis:
    image: redis
    volumes:
      - redis-data:/data:cached
    ports:
      - "6379:6379"
    logging:
      driver: none

volumes:
  db-data:
  redis-data:
