version: "3.8"
services:
  smtp:
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: none

  postgres:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:cached
    ports:
      - "5544:5432"
    environment:
      POSTGRES_PASSWORD: 123456
  #    logging:
  #      driver: none

  redis:
    image: redis
    volumes:
      - redis-data:/data:cached
    ports:
      - "6379:6379"
    logging:
      driver: none

volumes:
  db-data:
  redis-data:
